# Generated by Django 6.0.6 on 2026-07-18 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_status'),
        ('billing', '0004_alter_bill_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='service_type',
            field=models.CharField(choices=[('CONSULTATION', 'Consultation'), ('MEDICINE', 'Medicine'), ('LABORATORY', 'Laboratory'), ('ROOM', 'Room'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AlterField(
            model_name='bill',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
