# Generated by Django 6.0.6 on 2026-07-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_labreport_delete_lab'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labtest',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='labtest',
            old_name='test_name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='labtest',
            old_name='test_fee',
            new_name='price',
        ),
        migrations.AddField(
            model_name='labtest',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='normal_range',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='labtest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='requested_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
