# Generated by Django 6.0.6 on 2026-07-17 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0005_remove_labtest_appointment_remove_labtest_doctor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labrequest',
            options={'ordering': ['-requested_date']},
        ),
    ]
