# Generated by Django 6.0.6 on 2026-07-17 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0006_alter_labrequest_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labrequest',
            options={'ordering': ['-requested_at']},
        ),
        migrations.RenameField(
            model_name='labrequest',
            old_name='requested_date',
            new_name='requested_at',
        ),
        migrations.AddField(
            model_name='labrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_lab_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
