# Generated by Django 6.0.6 on 2026-07-17 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0007_alter_labrequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labreport',
            options={'ordering': ['-generated_at'], 'verbose_name': 'Laboratory Report', 'verbose_name_plural': 'Laboratory Reports'},
        ),
        migrations.RenameField(
            model_name='labreport',
            old_name='completed_date',
            new_name='generated_at',
        ),
        migrations.RemoveField(
            model_name='labreport',
            name='lab_test',
        ),
        migrations.RemoveField(
            model_name='labreport',
            name='result',
        ),
        migrations.AddField(
            model_name='labreport',
            name='lab_request',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='laboratory.labrequest'),
        ),
        migrations.AddField(
            model_name='labreport',
            name='report_image',
            field=models.ImageField(blank=True, null=True, upload_to='lab_reports/images/'),
        ),
        migrations.AddField(
            model_name='labreport',
            name='report_summary',
            field=models.TextField(blank=True, help_text='Overall findings and diagnosis.'),
        ),
        migrations.AddField(
            model_name='labreport',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Completed', 'Completed'), ('Verified', 'Verified')], default='Draft', max_length=20),
        ),
        migrations.AddField(
            model_name='labreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='labreport',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labreport',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_lab_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='lab_reports/pdf/'),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_lab_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
