# Generated by Django 6.0.6 on 2026-07-17 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0008_alter_labreport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labrequest',
            options={'ordering': ['-requested_date']},
        ),
        migrations.RenameField(
            model_name='labrequest',
            old_name='requested_at',
            new_name='requested_date',
        ),
    ]
