# Generated by Django 6.0.6 on 2026-07-17 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0009_alter_labrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='lab_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='laboratory.labrequest'),
        ),
    ]
