# Generated by Django 6.0.6 on 2026-07-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_stocktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
