# Generated by Django 6.0.6 on 2026-07-15 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_medicine_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='quantity',
        ),
    ]
