# Generated by Django 6.0.6 on 2026-07-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_prescription_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Dispensed', 'Dispensed')], default='Pending', max_length=20),
        ),
    ]
