# Generated by Django 6.0.6 on 2026-07-16 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_prescription_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrescriptionItems',
            new_name='PrescriptionItem',
        ),
    ]
