# Generated by Django 6.0.6 on 2026-07-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_rename_prescriptionitems_prescriptionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionitem',
            name='dosage',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
