# Generated by Django 6.0.6 on 2026-07-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_address_remove_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('doctor', 'doctor'), ('patient', 'patient')], max_length=20),
        ),
    ]
