# Generated by Django 6.0.6 on 2026-07-12 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='photo',
            new_name='profile_photo',
        ),
    ]
