# Generated by Django 6.0.6 on 2026-07-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_allergies_patient_chronic_disease_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
