# Generated by Django 6.0.6 on 2026-07-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='patient',
            name='relationship',
            field=models.CharField(default='', max_length=50),
        ),
    ]
