# Generated by Django 6.0.6 on 2026-07-07 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='photo',
            new_name='profile_photo',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='qualifications',
            new_name='qualification',
        ),
    ]
