# Generated by Django 6.0.6 on 2026-07-08 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctorsschedule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorsSchedule',
            new_name='DoctorSchedule',
        ),
    ]
